apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprodb
  labels:
    app: vprodb
spec:
  selector:
    metchLabels:
      app: vprodb
  replicas: 5
  template:
    metadata:
      labels:
        app: vprodb
    spec:
      containers:
        - name: vprodb
          image: vprofile/vprofiledb:V1
          args:
            - "--ignore-db-dir=lost+found"
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: vpro-db-data
          ports:
            - name: vprodb-port
              containerPort: 3306
            env:
              - name: MYSQL_ROOT_PASSWORD
                valueFrom: 
                secretKeyRef:
                  name: app-secret
                  keyL db-pass
      nodeSelector:
        zone: us-east-1a
        volumes:
          - name: vpro-db-data
            awsElasticBlockStore:
              volumeID:
                fsType: ext4
